_wandb:
    value:
        cli_version: 0.26.1
        e:
            ghsccocl51dxdrdxylogptujb21e5pfn:
                args:
                    - --data-path
                    - /home/evronba/MolGenOrg_MultiGoal/data/datasets/zinc_smiles_toy.text
                    - --tokenizer-path
                    - /home/evronba/MolGenOrg_MultiGoal/data/tokenizers/charTokenizer
                    - --save-path
                    - /home/evronba/MolGenOrg_MultiGoal/data/results
                    - --model-type
                    - DT
                    - --dataset-type
                    - DT_SMILES
                    - --config-path
                    - /home/evronba/MolGenOrg_MultiGoal/data/configs/sweeps_tmp/sweep_20260511_183828/exp2_goals4_accum64.toml
                    - --wandb-entity
                    - evronba-ben-gurion-university-of-the-negev
                    - --wandb-proj
                    - MolGen-Sweep-exp2_goals4_accum64-20260511_183828
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "204312743936"
                        used: "17021874176"
                email: evronba@post.bgu.ac.il
                executable: /home/evronba/.conda/envs/molgen/bin/python
                git:
                    commit: a6cb341e6f951ffce52d2d04cc1b05c8d1d231c4
                    remote: https://github.com/eyalmazuz/MolGen.git
                gpu: NVIDIA TITAN Xp
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-3b637b29-5d2d-0c8c-3427-2ae00b36ee12
                host: cs-1080-01.auth.ad.bgu.ac.il
                memory:
                    total: "269789401088"
                os: Linux-5.14.0-611.47.1.el9_7.x86_64-x86_64-with-glibc2.34
                program: -m scripts.pretrain
                python: CPython 3.11.15
                root: /home/evronba/MolGenOrg_MultiGoal
                slurm:
                    cluster_name: cluster
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "6"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: bshapira
                    job_cpus_per_node: "6"
                    job_end_time: "1778600354"
                    job_gid: "1945600513"
                    job_gpus: "1"
                    job_id: "17482385"
                    job_name: molgen_flex_test
                    job_nodelist: cs-1080-01
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1778513954"
                    job_uid: "343923174"
                    job_user: evronba
                    jobid: "17482385"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: cs-1080-01
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /home/evronba/MolGenOrg_MultiGoal
                    submit_host: ise-pheno-05.auth.ad.bgu.ac.il
                    task_pid: "113729"
                    tasks_per_node: "3"
                    topology_addr: cs-1080-01
                    topology_addr_pattern: node
                startedAt: "2026-05-11T15:40:42.756347Z"
                writerId: ghsccocl51dxdrdxylogptujb21e5pfn
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.11.15
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
model_config:
    value:
        block_size: 300
        dropout: 0.2
        ignore_index: 36
        max_seq_len: 100
        model_type: reward_conditioned
        n_embd: 100
        n_goals: 4
        n_head: 5
        n_layer: 3
        vocab_size: 37
reward:
    value:
        functions:
            - {}
            - scale:
                factor: 0.1
            - data_path: /home/evronba/MolGenOrg_MultiGoal/data/datasets/properties.csv
            - scale:
                factor: 0.5
        goal_conditioned: true
train_config:
    value:
        batch_size: 32
        betas:
            - 0.9
            - 0.95
        compile: false
        decay_lr: true
        device: cuda
        dtype: bfloat16
        eval_every: 10
        grad_clip: 1
        gradient_accumulation_steps: 64
        learning_rate: 8e-05
        load_checkpoint: false
        log_every: 10
        lr_decay_steps: 30000
        max_steps: 4000
        min_lr: 5e-06
        num_workers: 1
        seed: 42
        wandb_log: true
        warmup_steps: 2000
        weight_decay: 0.1
